version: '3.6'

services:
  library:
    build:
      context: library
      dockerfile: src/main/resources/library.dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - network1
  order:
    build:
      context: order
      dockerfile: src/main/resources/order.dockerfile
    expose:
      - 8080
    ports:
      - "8090:8080"
    networks:
      - network1
  payment:
    build:
      context: payment
      dockerfile: src/main/resources/payment.dockerfile
    expose:
      - 8080
    ports:
      - "8070:8080"
    networks:
      - network1

networks:
  network1:
    driver: bridge